---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/main/netbox-celery/docs"
site_dir: "dist/docs"
site_name: "Netbox Celery Documentation"
site_url: "https://netbox-celery.readthedocs.io/en/latest/"
repo_url: "https://github.com/opticore/netbox-celery"
copyright: "Copyright &copy; The Authors"
theme:
  name: material
  custom_dir: docs/_theme/
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to Light Mode

# needed for RTD version flyout menu
# jquery is not (yet) injected by RTD automatically and it might be dropped
# as a dependency in the future
extra_javascript:
  - "https://code.jquery.com/jquery-3.6.0.min.js"

extra:
  generator: false
markdown_extensions:
  - "admonition"
  - "toc":
      permalink: true
  - "attr_list"
  - "md_in_html"
  - "pymdownx.details"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"

plugins:
  - "search"
  - "include-markdown"
  - "mkdocs-version-annotations"
  - "mkdocstrings":
      default_handler: "python"
      handlers:
        python:
          paths: ["."]
          options:
            heading_level: 1
            show_root_heading: true
            show_root_members_full_path: true

nav:
  - Overview: "index.md"
  - Documentation:
      - Installation:
          - Quick Start: "install.md"
      - Celery Beat:
          - "beat.md"
      - Models:
          - "models.md"
      - Tasks:
          - "tasks.md"