# Generated by Django 4.1.7 on 2023-03-23 10:55

from django.db import migrations, models
import utilities.json


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_celery", "0003_celeryresult_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celeryresult",
            name="custom_field_data",
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
    ]
