# Generated by Django 4.2.4 on 2023-08-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_celery", "0004_alter_celeryresult_custom_field_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celerylogentry",
            name="log_level",
            field=models.CharField(db_index=True, default=20, max_length=64),
        ),
    ]
